packages:
  - artifacts/mrz-scanner

catalog:
  '@tanstack/react-query': ^5.90.21
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  react: 19.1.0
  react-dom: 19.1.0
  zod: ^3.25.76

autoInstallPeers: false
